apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: auth-service
  namespace: default
# Allow traffic to auth-service from api-gateway
spec:
  destination:
    name: auth-service
  sources:
    - name: api-gateway
      action: allow