# Documentation about Garden projects can be found at https://docs.garden.io/using-garden/projects
# Reference for Garden projects can be found at https://docs.garden.io/reference/project-config

apiVersion: garden.io/v1
kind: Project
name: poll-app

defaultEnvironment: local
environments:
  - name: local
    defaultNamespace: garden-local
  - name: remote
    defaultNamespace: garden-remote-${local.username}
  - name: staging
    production: true
    defaultNamespace: staging

providers:
  - name: local-kubernetes
    environments:
      - local
    context: minikube
  - name: kubernetes
    environments:
      - remote
    context: # ... your remote development kubecontext here
  - name: kubernetes
    environments:
      - staging
    context: # ... your staging kubecontext here

scan:
  include:
    - apps/**/*
---
kind: Build
name: build-all
type: exec
spec:
  command: [yarn, nx, run, api-gateway:build:production]
