endpoints:
  - name: users
    description: Users service
    url: http://localhost:3001/graphql
  - name: auth
    description: Authentication service
    url: http://localhost:3002/graphql
  - name: posts
    description: Posts service
    url: http://localhost:3003/graphql