fragment FeedMultipleChoiceQuestion on MultipleChoiceQuestion {
  type
  question
  options
  voteTotals
}

fragment FeedResponse on Response {
  id
  type
  ...MultipleChoiceResponseFragment
  post {
    id
  }
  author {
    id
    ...ProfileData
  }
  content
  createdAt
}

fragment FeedPost on Post {
  id
  author {
    id
    ...ProfileData
  }
  content {
    ...FeedMultipleChoiceQuestion
  }
  responses(last: 3, orderBy: "createdAt") {
    edges {
      node {
        ...FeedResponse
      }
    }
  }
  myResponses(first: 1) {
    edges {
      node {
        ...FeedResponse
      }
    }
  }
  caption
  createdAt
  updatedAt
}
