query getUserName($id: String!) {
  user(id: $id) {
    displayName
  }
}

query getProfile($id: String!) {
  user(id: $id) {
    displayName
    profilePicture
  }
}

mutation CreateUser($id: String!, $args: CreateUserArgs!) {
  createUser(id: $id, args: $args) {
    id
  }
}
