apiVersion: v2
name: poll-app/consul
description: The helm chart for consul running in the poll app
type: application
# Chart version is the version of the chart, not the application.
version: 0.1.0
# The application version is the version of the application the chart installs.
appVersion: "1.16.0"
dependencies:
  - name: consul
    version: 1.3.0
    repository: https://helm.releases.hashicorp.com