import AppFooter from './footer';
import './global.css';

export const metadata = {
  title: 'Welcome to poll-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <AppFooter />
      </body>
    </html>
  );
}

// TODO - is this right?
export const dynamic = 'force-dynamic';
