import { Theme } from '@radix-ui/themes';
import Providers from '../components/providers';
import AppFooter from './footer';
import './global.css';

export const metadata = {
  title: 'Welcome to poll-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Theme appearance="dark">{children}</Theme>
        </Providers>
        <AppFooter />
      </body>
    </html>
  );
}
