import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import './global.css';

export const metadata = {
  title: 'Welcome to poll-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme appearance="dark">
          {children}
        </Theme>
      </body>
    </html>
  );
}
