---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend 
  namespace: default
# Allow traffic from nginx to frontend
spec:
  destination:
    name: frontend
  sources:
    - name: nginx
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api-gateway
  namespace: default
# Allow traffic to api-gateway
spec:
  destination:
    name: api-gateway
  sources:
    - name: nginx
      action: allow
    - name: frontend
      action: allow
    - name: user-service
      action: allow
    - name: auth-service
      action: allow
    - name: post-service
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: user-service
  namespace: default
# Allow traffic to user-service from api-gateway
spec:
  destination:
    name: user-service
  sources:
    - name: api-gateway
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: auth-service
  namespace: default
# Allow traffic to auth-service from api-gateway
spec:
  destination:
    name: auth-service
  sources:
    - name: api-gateway
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: post-service
  namespace: default
# Allow traffic to post-service from api-gateway
spec:
  destination:
    name: post-service
  sources:
    - name: api-gateway
      action: allow
---