// libs/ui-kit/util/src/tailwind/tailwind.config.js

const { join } = require('path');

const defaultTheme = require('tailwindcss/defaultTheme');
const TailwindAnimate = require('tailwindcss-animate');

module.exports = {
  content: [
    // relative path by consumer app
    './{app,pages,components}/**/*.{js,jsx,ts,tsx}',
    // path to ui-kit components (relative to current dir)
    join(__dirname, '../../../ui/**/*.{js,jsx,ts,tsx}'),
  ],
  theme: {
    extend: {
      screens: {
        'xs': '375px',
      },
      colors: {
        foreground: {
          DEFAULT: 'var(--fgColor-default)',
          muted: 'var(--fgColor-muted)',
          emphasis: 'var(--fgColor-emphasis)',
          inverse: 'var(--fgColor-inverse)',
          white: 'var(--fgColor-white)',
          black: 'var(--fgColor-black)',
          disabled: 'var(--fgColor-disabled)',
          link: 'var(--fgColor-link)',
          neutral: 'var(--fgColor-neutral)',
          accent: 'var(--fgColor-accent)',
          success: 'var(--fgColor-success)',
          open: 'var(--fgColor-open)',
          attention: 'var(--fgColor-attention)',
          severe: 'var(--fgColor-severe)',
          danger: 'var(--fgColor-danger)',
          closed: 'var(--fgColor-closed)',
          done: 'var(--fgColor-done)',
          upsell: 'var(--fgColor-upsell)',
        },
        background: {
          DEFAULT: 'var(--bgColor-default)',
          muted: 'var(--bgColor-muted)',
          inset: 'var(--bgColor-inset)',
          emphasis: 'var(--bgColor-emphasis)',
          inverse: 'var(--bgColor-inverse)',
          white: 'var(--bgColor-white)',
          black: 'var(--bgColor-black)',
          disabled: 'var(--bgColor-disabled)',
          transparent: 'var(--bgColor-transparent)',
          "neutral-muted": 'var(--bgColor-neutral-muted)',
          "neutral-emphasis": 'var(--bgColor-neutral-emphasis)',
          "accent-muted": 'var(--bgColor-accent-muted)',
          "accent-emphasis": 'var(--bgColor-accent-emphasis)',
          "success-muted": 'var(--bgColor-success-muted)',
          "success-emphasis": 'var(--bgColor-success-emphasis)',
          "open-muted": 'var(--bgColor-open-muted)',
          "open-emphasis": 'var(--bgColor-open-emphasis)',
          "attention-muted": 'var(--bgColor-attention-muted)',
          "attention-emphasis": 'var(--bgColor-attention-emphasis)',
          "severe-muted": 'var(--bgColor-severe-muted)',
          "severe-emphasis": 'var(--bgColor-severe-emphasis)',
          "danger-muted": 'var(--bgColor-danger-muted)',
          "danger-emphasis": 'var(--bgColor-danger-emphasis)',
          "closed-muted": 'var(--bgColor-closed-muted)',
          "closed-emphasis": 'var(--bgColor-closed-emphasis)',
          "done-muted": 'var(--bgColor-done-muted)',
          "done-emphasis": 'var(--bgColor-done-emphasis)',
          "upsell-muted": 'var(--bgColor-upsell-muted)',
          "upsell-emphasis": 'var(--bgColor-upsell-emphasis)',
          "sponsors-muted": 'var(--bgColor-sponsors-muted)',
          "sponsors-emphasis": 'var(--bgColor-sponsors-emphasis)',
        },
        border: {
          DEFAULT: 'var(--borderColor-default)',
          muted: 'var(--borderColor-muted)',
          emphasis: 'var(--borderColor-emphasis)',
          disabled: 'var(--borderColor-disabled)',
          transparent: 'var(--borderColor-transparent)',
          translucent: 'var(--borderColor-translucent)',
          "neutral-muted": 'var(--borderColor-neutral-muted)',
          "neutral-emphasis": 'var(--borderColor-neutral-emphasis)',
          "accent-muted": 'var(--borderColor-accent-muted)',
          "accent-emphasis": 'var(--borderColor-accent-emphasis)',
          "success-muted": 'var(--borderColor-success-muted)',
          "success-emphasis": 'var(--borderColor-success-emphasis)',
          "open-muted": 'var(--borderColor-open-muted)',
          "open-emphasis": 'var(--borderColor-open-emphasis)',
          "attention-muted": 'var(--borderColor-attention-muted)',
          "attention-emphasis": 'var(--borderColor-attention-emphasis)',
          "severe-muted": 'var(--borderColor-severe-muted)',
          "severe-emphasis": 'var(--borderColor-severe-emphasis)',
          "danger-muted": 'var(--borderColor-danger-muted)',
          "danger-emphasis": 'var(--borderColor-danger-emphasis)',
          "closed-muted": 'var(--borderColor-closed-muted)',
          "closed-emphasis": 'var(--borderColor-closed-emphasis)',
          "done-muted": 'var(--borderColor-done-muted)',
          "done-emphasis": 'var(--borderColor-done-emphasis)',
          "upsell-muted": 'var(--borderColor-upsell-muted)',
          "upsell-emphasis": 'var(--borderColor-upsell-emphasis)',
          "sponsors-muted": 'var(--borderColor-sponsors-muted)',
          "sponsors-emphasis": 'var(--borderColor-sponsors-emphasis)',
        },
        ring: 'var(--focus-outlineColor)',
      },
      borderRadius: {
        DEFAULT: 'var(--border-radius-default)',
        sm: 'var(--border-radius-sm)',
        md: 'var(--border-radius-md)',
        lg: 'var(--border-radius-lg)',
        xl: 'var(--border-radius-xl)',
        full: 'var(--border-radius-full)',
      },
      borderWidth: {
        thin: 'var(--border-width-thin)',
        thick: 'var(--border-width-thick)',
        thicker: 'var(--border-width-thicker)',
      },
      boxShadow: {
        "inset": 'var(--shadow-inset)',
        "resting-xs": 'var(--shadow-resting-xsmall)',
        "resting-sm": 'var(--shadow-resting-small)',
        "resting-md": 'var(--shadow-resting-medium)',
        "floating-sm": 'var(--shadow-floating-small)',
        "floating-md": 'var(--shadow-floating-medium)',
        "floating-lg": 'var(--shadow-floating-large)',
        "floating-xl": 'var(--shadow-floating-xlarge)',
      },
      keyframes: {
        'slide-up': {
          from: { opacity: 0, transform: 'translateY(10px)' },
          to: { opacity: 1, transform: 'translateY(0)' }
        },
        'slide-down': {
          from: { opacity: 0, transform: 'translateY(-10px)' },
          to: { opacity: 1, transform: 'translateY(0)' }
        },
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'slide-up': 'slide-up 0.2s ease-out',
        'slide-down': 'slide-down 0.2s ease-out',
      },
    },
  },
  plugins: [TailwindAnimate],
  darkMode: ['class'],
};